Fix missing jar and args passing for Pod deployment
canonical/kserve-rocks pull request #7
Opened 2023-10-26 08:20 UTC by misohu

Resolving this issue https://github.com/canonical/kserve-rocks/issues/6 by wrapping the rock into docker image with correct ENTRYPOINT. Moreover I added also missing jar library which was not coppied from build stage

2023-10-26 13:01 UTC, i-chvets commented
LGTM. Approved.
NOTE: Having ROCK wrapped in Docker defeats the purpose of having ROCKs. It makes the whole idea of using ROCKs in their current feature state very flawed. It would make sense to wait for Rockcraft to include features then to build ROCKs for sake of building ROCKs.

2023-10-26 13:01 UTC, i-chvets approved these changes
Approved.

2023-10-26 13:18 UTC, SamirPS requested changes

2023-10-26 13:18 UTC, SamirPS commented on pmmlserver/rockcraft.yaml
> +    - python3.9
do you really need all this overlay package ? some can be on stage-packages no ?

2023-10-27 12:23 UTC, SamirPS approved these changes

2023-10-27 12:23 UTC, SamirPS commented
> LGTM. Approved. NOTE: Having ROCK wrapped in Docker defeats the purpose of having ROCKs. It makes the whole idea of using ROCKs in their current feature state very flawed. It would make sense to wait for Rockcraft to include features that support our use cases then to build ROCKs for sake of building ROCKs.

i agree with you

2023-10-30 11:59 UTC, merged